[workspace]
resolver = "2"
members = [
    ".",
    "blahctl",
    "blahd",
]
default-members = ["blahd"]

[package]
name = "blah"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
bitflags = "2"
bitflags_serde_shim = "0.2"
ed25519-dalek = "2.1"
hex = { version = "0.4", features = ["serde"] }
html-escape = "0.2"
rand_core = "0.6"
rusqlite = { version = "0.32", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["serde"] }

[dev-dependencies]
syn = { version = "2.0.76", features = ["full", "visit"] }
