[package]
name = "blah"
version = "0.0.0"
edition = "2021"

# TODO: Shrink dependencies.
[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["tokio"] }
bitflags = "2.6.0"
bitflags_serde_shim = "0.2.5"
clap = { version = "4.5.16", features = ["derive"] }
ed25519-dalek = { version = "2.1.1", features = ["digest", "serde"] }
futures-util = "0.3.30"
hex = { version = "0.4.3", features = ["serde"] }
html-escape = "0.2.13"
humantime = "2.1.0"
rand_core = "0.6.4"
rusqlite = { version = "0.32.1", features = ["uuid"] }
sd-notify = "0.4.2"
serde = { version = "1.0.209", features = ["derive"] }
serde-aux = "4.5.0"
serde-constant = "0.1.0"
serde_json = "1.0.127"
serde_tuple = "0.5.0"
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread", "sync"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tower-http = { version = "0.5.2", features = ["cors", "limit"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.10.0", features = ["serde", "v4"] }

[dev-dependencies]
syn = { version = "2.0.76", features = ["full", "visit"] }

[workspace]
members = [ "./blahctl" ]
