[workspace]
resolver = "2"
members = [
    "blah-types",
    "blahctl",
    "blahd",
]
default-members = ["blahd"]

[workspace.lints.clippy]
allow_attributes = "warn"
dbg_macro = "warn"
print_stderr = "warn"
print_stdout = "warn"
todo = "warn"
unwrap_used = "warn"
